<Action id="26629" issue="18239" author="muralisr" type="comment" created="2017-06-16 21:02:25.0" updateauthor="muralisr" updated="2017-06-16 21:02:25.0"> <body><! CDATA  ~latitiah    I'd have expected problems with TLS than other way round.   Plus I mostly run without TLS in the chaincode dev env and have never run into chaincode problems because of running in non-TLS TLS issues..  I assume all old chaincode images were cleaned up etc ?   can you include steps to recreate (simple steps deeply appreciated :-) ...last time I had to spend the entire night deciphering a defect _that_shall_not_be_named :-)     ></body> </Action>
<Action id="26650" issue="18239" author="latitiah" type="comment" created="2017-06-17 13:09:01.0" updateauthor="latitiah" updated="2017-06-17 13:09:01.0"> <body><! CDATA  My apologies for the confusion. I'm not running these tests manually, so I'm extracting the steps from code.     That said,  I've spoken to a couple of people on this issue.  I'm going to rerun this setting the policy.  I have no policy set in this test run.  I'll post the commands and results when I'm done. Thanks!   ></body> </Action>
<Action id="26655" issue="18239" author="muralisr" type="comment" body=" ~latitiah  Certainly. Do let me know (in RC if you prefer) if I can help." created="2017-06-17 13:57:45.0" updateauthor="muralisr" updated="2017-06-17 13:57:45.0"/>
<Action id="26665" issue="18239" author="muralisr" type="comment" created="2017-06-17 18:21:27.0" updateauthor="muralisr" updated="2017-06-17 18:21:27.0"> <body><! CDATA  ~latitiah  FWIW... take it with a pinch of salt please as you may be running into something else but I was able to recreate something that had the same look and feel.   I started my simple *docker-compose up* and had it running.  While that was running,  I did the standard e2e_cli test it complained (as expected) "cli" was in use.  I did a *docker-compose down* on the simple test.  Started the e2e_cli test again immediately and saw the following that looked a close to the error you were seeing.  {code:java} 2017-06-17 18:03:55.942 UTC  msp  getMspConfig -> INFO 001 intermediate certs folder not found at  /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/intermediatecerts . Skipping.:  stat /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/intermediatecerts: no such file or directory  2017-06-17 18:03:55.942 UTC  msp  getMspConfig -> INFO 002 crls folder not found at  /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/intermediatecerts . Skipping.:  stat /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/crls: no such file or directory  2017-06-17 18:03:55.942 UTC  msp  getMspConfig -> INFO 003 MSP configuration file not found at  /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/config.yaml :  stat /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/config.yaml: no such file or directory  2017-06-17 18:03:55.977 UTC  msp  GetLocalMSP -> DEBU 004 Returning existing local MSP 2017-06-17 18:03:55.977 UTC  msp  GetDefaultSigningIdentity -> DEBU 005 Obtaining default signing identity 2017-06-17 18:03:55.988 UTC  grpc  Printf -> DEBU 006 Failed to dial orderer.example.com:7050: connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority (possibly because of \"x509: ECDSA verification failure\" while trying to verify candidate authority certificate \"ca.example.com\")"; please retry. Error: Error connecting due to rpc error: code = Internal desc = connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority (possibly because of \"x509: ECDSA verification failure\" while trying to verify candidate authority certificate \"ca.example.com\")"  {code}   Once I cleaned the env and restarted the e2e_cli, it worked.  ></body> </Action>
<Action id="26690" issue="18239" author="mastersingh24" type="comment" body="setting to unverified because there still does not seem to be a way to reproduce this" created="2017-06-18 13:26:32.0" updateauthor="mastersingh24" updated="2017-06-18 13:26:32.0"/>
<Action id="26772" issue="18239" author="latitiah" type="comment" created="2017-06-19 16:18:53.0" updateauthor="latitiah" updated="2017-06-19 16:18:53.0"> <body><! CDATA Hi Murali, I've been running this test through behave. Once these are pushed it would be much easier to point you to the exact steps that were executed.  My apologies for the confusion. I checked my environment vars and everything looked fine at a glance and I was still running into some issues - even after the policy addition. So to be absolutely sure, I reloaded my vm and rebuilt everything - It worked! I'm not sure exactly what I had set wrong, but I'm closing this issue. Thanks for your patience and help.  ></body> </Action>
<Action id="26779" issue="18239" author="muralisr" type="comment" body=" ~latitiah  thanks much keeping at it .... at some point it may be worth getting to the bottom of this in to help others running into this." created="2017-06-19 17:27:57.0" updateauthor="muralisr" updated="2017-06-19 17:27:57.0"/>
<Action id="26892" issue="18239" author="latitiah" type="comment" created="2017-06-20 20:36:55.0" updateauthor="latitiah" updated="2017-06-20 20:39:22.0"> <body><! CDATA Reopening this issue since I just saw this happen again. Once again, I have verified that the environment variables were clean of any "stray" config settings; the docker builds and images were clean; I have checked memory and number of inodes used. So far nothing stands out as being an obvious culprit.   Environment when executing the tests: {code} ('Current env:', {'GOPATH': '/opt/gopath', 'GOROOT': '/opt/go', 'VAGRANT': '1', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'SSH_CLIENT': '10.0.2.2 59405 22', 'LOGNAME': 'vagrant', 'USER': 'vagrant', 'HOME': '/home/vagrant', 'PATH': '/home/vagrant/bin:/home/vagrant/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/go/bin:/opt/gopath/bin:/hyperledger/devenv/tools:/hyperledger/build/bin', 'LANG': 'en_US', 'TERM': 'xterm', 'SHELL': '/bin/bash', 'LANGUAGE': 'en_US:', 'SHLVL': '1', 'CORE_PEER_NETWORKID': 'c725fbdc55f111e783a70800275fb08f', 'XDG_RUNTIME_DIR': '/run/user/1000', 'CGO_CFLAGS': ' ', 'XDG_SESSION_ID': '2', '_': '/usr/local/bin/behave', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'SSH_TTY': '/dev/pts/0', 'OLDPWD': '/opt/gopath/src/github.com/hyperledger/fabric-test/test/feature', 'COMPOSE_PROJECT_NAME': 'c725fbdc55f111e783a70800275fb08f', 'PWD': '/opt/gopath/src/github.com/hyperledger/fabric/test/feature', 'MAIL': '/var/mail/vagrant', 'SSH_CONNECTION': '10.0.2.2 59405 10.0.2.15 22'}) {code}   Memory: {code} total        used        free      shared  buff/cache   available Mem:           3.9G        119M        1.3G         32M        2.5G        3.4G Swap:          509M        9.0M        501M {code}  Inodes: {code} Filesystem      Inodes  IUsed   IFree IUse% Mounted on /dev/sda1      2588672 526183 2062489   21% / {code}  ></body> </Action>
<Action id="27289" issue="18239" author="latitiah" type="comment" created="2017-06-23 17:21:04.0" updateauthor="latitiah" updated="2017-06-23 17:21:04.0"> <body><! CDATA It looks like this may have to do with the number of chaincode images that are still around. This happened again and the number of docker chaincode images was at 276 - they were not being cleaned up. When I removed them, this error seemed to go away. It may have been a fluke, but seeing as this should be cleaned up anyway, I'm going to chalk this up to needing the clean up.   ></body> </Action>
<Action id="27349" issue="18239" author="weeds" type="comment" body="Latitia- i feel like other people have encountered this when they have not done some cleaning up of the system.  Seems like we should add something in the documentation that if they reload their system- they need to do sufficient clean up.  I could see developers do this same scenario and not realize how important this is and run into errors.  What do you think? Something for the doc if not already there?" created="2017-06-26 12:37:15.0" updateauthor="weeds" updated="2017-06-26 12:37:15.0"/>
<Action id="27379" issue="18239" author="latitiah" type="comment" body="Hi  ~weeds  - I asked where the best place for this information would be. It was suggested that this should be an entry on stackoverflow. " created="2017-06-26 19:14:45.0" updateauthor="latitiah" updated="2017-06-26 19:14:45.0"/>
<Action id="54752" issue="18239" author="javapriyan" type="comment" body=" ~latitiah  Thanks for logging this JIRA. I am facing the same issue with all the peers when I launch a new custom cluster from the official sample first-network. Can you please help me with what are the possible clean up has to be done? Thanks ! " created="2018-12-13 06:29:50.0" updateauthor="javapriyan" updated="2018-12-13 06:29:50.0"/>
<Action id="54754" issue="18239" author="javapriyan" type="comment" body="I was abruptly cleaning the docker images. After going through this, I have inspected the ./byfn.sh down commands. That&apos;s just did the job. Hope this may help others" created="2018-12-13 06:42:59.0" updateauthor="javapriyan" updated="2018-12-13 06:42:59.0"/>
