<Issue id="12519" key="FABN-336" number="336" project="10604" reporter="nishi" creator="nishi" type="10004" summary=" node-SDK  getNextTCert API in member class in Node SDK fetched tcert even when we pass a non-exiting attibute" priority="3" resolution="10000" status="6" created="2016-08-22 13:32:39.0" updated="2018-07-19 00:53:41.0" resolutiondate="2017-02-08 15:31:29.0" votes="0" watches="2" workflowId="34067"> <description><! CDATA Passed in a non-existing attribute for user alice to getNextTCert by calling alice.getNextTCert( 'fail' ,function(err, tcert) in the test.  Expected Result:  Test to fail since 'fail' is not an attribute defined for alice in membersrvc.yaml  Actual Result:  Test passed and generated a TCert.  commit 346f9fb  ></description> </Issue>
