<Action id="46955" issue="31666" author="rajeshkalaria" type="comment" created="2018-07-05 14:11:08.0" updateauthor="rajeshkalaria" updated="2018-07-05 14:11:08.0"> <body><! CDATA Here are details logs related to the error:     TRACE|indy::api::crypto             |                  src/api/crypto.rs:274 | indy_crypto_verify: entities >>> signer_vk: "5dszRBEEktHp3jDF6NTKw31smnyazWb9d5hB2GmvqLQd", message_raw:  76, 116, 69, 103, 72, 121, 100, 66, 120, 56, 117, 113, 51, 67, 69, 57, 97, 98, 105, 116, 72, 82, 66, 113, 90, 52, 77, 52, 117, 86, 90, 57, 109, 100, 89, 86, 110, 115, 69, 100, 56, 85, 101, 50, 82, 112, 105, 84, 118, 107, 88, 65, 106, 110, 81, 85, 119, 55, 115, 116, 50, 109, 71, 65, 114, 81 , message_len: 66, signature_raw:  80, 156, 4, 203, 26, 222, 180, 208, 197, 111, 22, 88, 77, 17, 79, 13, 231, 227, 48, 26, 126, 93, 76, 154, 114, 31, 42, 156, 110, 84, 84, 66, 202, 172, 61, 139, 95, 11, 230, 16, 150, 116, 249, 71, 150, 134, 158, 50, 138, 116, 125, 218, 176, 71, 49, 28, 230, 103, 172, 226, 77, 69, 110, 12 , signature_len: 64  TRACE|indy::api::crypto             |                  src/api/crypto.rs:291 | indy_crypto_verify: <<< res: Success  INFO|indy::commands                |                src/commands/mod.rs:110 | CryptoCommand command received  INFO|indy::commands::crypto        |             src/commands/crypto.rs:104 | CryptoVerify command received  DEBUG|indy::commands::crypto        |             src/commands/crypto.rs:166 | crypto_verify >>> their_vk: "5dszRBEEktHp3jDF6NTKw31smnyazWb9d5hB2GmvqLQd", msg:  76, 116, 69, 103, 72, 121, 100, 66, 120, 56, 117, 113, 51, 67, 69, 57, 97, 98, 105, 116, 72, 82, 66, 113, 90, 52, 77, 52, 117, 86, 90, 57, 109, 100, 89, 86, 110, 115, 69, 100, 56, 85, 101, 50, 82, 112, 105, 84, 118, 107, 88, 65, 106, 110, 81, 85, 119, 55, 115, 116, 50, 109, 71, 65, 114, 81 , signature:  80, 156, 4, 203, 26, 222, 180, 208, 197, 111, 22, 88, 77, 17, 79, 13, 231, 227, 48, 26, 126, 93, 76, 154, 114, 31, 42, 156, 110, 84, 84, 66, 202, 172, 61, 139, 95, 11, 230, 16, 150, 116, 249, 71, 150, 134, 158, 50, 138, 116, 125, 218, 176, 71, 49, 28, 230, 103, 172, 226, 77, 69, 110, 12   TRACE|indy::services::crypto        |         src/services/crypto/mod.rs:366 | validate_key >>> vk: "5dszRBEEktHp3jDF6NTKw31smnyazWb9d5hB2GmvqLQd"  TRACE|indy::services::crypto        |         src/services/crypto/mod.rs:386 | validate_key <<< res: ()  TRACE|indy::services::crypto        |         src/services/crypto/mod.rs:169 | verify >>> their_vk: "5dszRBEEktHp3jDF6NTKw31smnyazWb9d5hB2GmvqLQd", msg:  76, 116, 69, 103, 72, 121, 100, 66, 120, 56, 117, 113, 51, 67, 69, 57, 97, 98, 105, 116, 72, 82, 66, 113, 90, 52, 77, 52, 117, 86, 90, 57, 109, 100, 89, 86, 110, 115, 69, 100, 56, 85, 101, 50, 82, 112, 105, 84, 118, 107, 88, 65, 106, 110, 81, 85, 119, 55, 115, 116, 50, 109, 71, 65, 114, 81 , signature:  80, 156, 4, 203, 26, 222, 180, 208, 197, 111, 22, 88, 77, 17, 79, 13, 231, 227, 48, 26, 126, 93, 76, 154, 114, 31, 42, 156, 110, 84, 84, 66, 202, 172, 61, 139, 95, 11, 230, 16, 150, 116, 249, 71, 150, 134, 158, 50, 138, 116, 125, 218, 176, 71, 49, 28, 230, 103, 172, 226, 77, 69, 110, 12   TRACE|indy::services::crypto        |         src/services/crypto/mod.rs:189 | verify <<< valid: true  DEBUG|indy::commands::crypto        |             src/commands/crypto.rs:172 | crypto_verify <<< res: true  TRACE|indy::api::crypto             |                  src/api/crypto.rs:284 | indy_crypto_verify: valid: true  TRACE|indy::api::crypto             |                  src/api/crypto.rs:266 | indy_crypto_verify: >>> signer_vk: 0x7ff56403d9e0, message_raw: 0x7ff564079c70, message_len: 66, signature_raw: 0x7ff564079cc0, signature_len: 64  TRACE|indy::api::crypto             |                  src/api/crypto.rs:274 | indy_crypto_verify: entities >>> signer_vk: "5UuNmKbKqUBcnmQDpea4EVT8Yfi7gTDNfs8FXS7ZW65F", message_raw:  65, 50, 113, 71, 114, 57, 105, 86, 86, 114, 87, 115, 110, 51, 83, 119, 83, 50, 114, 103, 55, 119, 53, 118, 87, 78, 90, 50, 54, 77, 88, 107, 121, 100, 74, 115, 118, 100, 97, 84, 74, 55, 77, 111, 52, 65, 116, 102, 78, 70, 113, 74, 57, 69, 84, 120, 83, 117, 69, 99, 120, 119, 85, 89, 88, 109 , message_len: 66, signature_raw:  66, 67, 238, 46, 182, 232, 177, 2, 154, 248, 152, 220, 189, 35, 78, 99, 22, 121, 4, 252, 83, 0, 23, 255, 66, 67, 199, 33, 99, 187, 69, 107, 101, 40, 155, 252, 43, 22, 20, 39, 137, 173, 139, 126, 32, 56, 16, 26, 34, 188, 202, 228, 17, 193, 246, 71, 2, 62, 72, 169, 68, 132, 159, 0 , signature_len: 64  TRACE|indy::api::crypto             |                  src/api/crypto.rs:291 | indy_crypto_verify: <<< res: Success  INFO|indy::commands                |                src/commands/mod.rs:110 | CryptoCommand command received  INFO|indy::commands::crypto        |             src/commands/crypto.rs:104 | CryptoVerify command received  DEBUG|indy::commands::crypto        |             src/commands/crypto.rs:166 | crypto_verify >>> their_vk: "5UuNmKbKqUBcnmQDpea4EVT8Yfi7gTDNfs8FXS7ZW65F", msg:  65, 50, 113, 71, 114, 57, 105, 86, 86, 114, 87, 115, 110, 51, 83, 119, 83, 50, 114, 103, 55, 119, 53, 118, 87, 78, 90, 50, 54, 77, 88, 107, 121, 100, 74, 115, 118, 100, 97, 84, 74, 55, 77, 111, 52, 65, 116, 102, 78, 70, 113, 74, 57, 69, 84, 120, 83, 117, 69, 99, 120, 119, 85, 89, 88, 109 , signature:  66, 67, 238, 46, 182, 232, 177, 2, 154, 248, 152, 220, 189, 35, 78, 99, 22, 121, 4, 252, 83, 0, 23, 255, 66, 67, 199, 33, 99, 187, 69, 107, 101, 40, 155, 252, 43, 22, 20, 39, 137, 173, 139, 126, 32, 56, 16, 26, 34, 188, 202, 228, 17, 193, 246, 71, 2, 62, 72, 169, 68, 132, 159, 0   TRACE|indy::services::crypto        |         src/services/crypto/mod.rs:366 | validate_key >>> vk: "5UuNmKbKqUBcnmQDpea4EVT8Yfi7gTDNfs8FXS7ZW65F"  TRACE|indy::services::crypto        |         src/services/crypto/mod.rs:386 | validate_key <<< res: ()  TRACE|indy::services::crypto        |         src/services/crypto/mod.rs:169 | verify >>> their_vk: "5UuNmKbKqUBcnmQDpea4EVT8Yfi7gTDNfs8FXS7ZW65F", msg:  65, 50, 113, 71, 114, 57, 105, 86, 86, 114, 87, 115, 110, 51, 83, 119, 83, 50, 114, 103, 55, 119, 53, 118, 87, 78, 90, 50, 54, 77, 88, 107, 121, 100, 74, 115, 118, 100, 97, 84, 74, 55, 77, 111, 52, 65, 116, 102, 78, 70, 113, 74, 57, 69, 84, 120, 83, 117, 69, 99, 120, 119, 85, 89, 88, 109 , signature:  66, 67, 238, 46, 182, 232, 177, 2, 154, 248, 152, 220, 189, 35, 78, 99, 22, 121, 4, 252, 83, 0, 23, 255, 66, 67, 199, 33, 99, 187, 69, 107, 101, 40, 155, 252, 43, 22, 20, 39, 137, 173, 139, 126, 32, 56, 16, 26, 34, 188, 202, 228, 17, 193, 246, 71, 2, 62, 72, 169, 68, 132, 159, 0   TRACE|indy::services::crypto        |         src/services/crypto/mod.rs:189 | verify <<< valid: true  DEBUG|indy::commands::crypto        |             src/commands/crypto.rs:172 | crypto_verify <<< res: true  TRACE|indy::api::crypto             |                  src/api/crypto.rs:284 | indy_crypto_verify: valid: true  2018-07-05 19:34:15.884  actorSpecSystem46644-akka.actor.default-dispatcher-3  DEBUG c.e.agency.common.vault.WalletAPI - about to store their key => wallet name: 51ce4d101cf1f71be5f40fe14c57b21a6ccdf63c065bd7c86a7f17da4ed50d12, key: StoreTheirKeyParam(MEWn6Vh1KsdkSZvHTvuGQG,C2c5BptNrcgb9usyck8TKNhq3xFmMvZZA3SZpmW4kLXP)  2018-07-05 19:34:15.885  actorSpecSystem46644-akka.actor.default-dispatcher-3  DEBUG c.e.agency.common.vault.WalletAPI - about to store their key => wallet name: 51ce4d101cf1f71be5f40fe14c57b21a6ccdf63c065bd7c86a7f17da4ed50d12, key: StoreTheirKeyParam(A2qGr9iVVrWsn3SwS2rg7w,5vWNZ26MXkydJsvdaTJ7Mo4AtfNFqJ9ETxSuEcxwUYXm)  TRACE|indy::api::did                |                     src/api/did.rs:222 | indy_store_their_did: >>> wallet_handle: 3, identity_json: 0x7ff564046200  TRACE|indy::api::did                |                     src/api/did.rs:227 | indy_store_their_did: entities >>> wallet_handle: 3, identity_json: "\{\"did\":\"MEWn6Vh1KsdkSZvHTvuGQG\",\"verkey\":\"C2c5BptNrcgb9usyck8TKNhq3xFmMvZZA3SZpmW4kLXP\"}"  TRACE|indy::api::did                |                     src/api/did.rs:242 | indy_store_their_did: <<< res: Success  INFO|indy::commands                |                src/commands/mod.rs:122 | DidCommand command received  INFO|indy::commands::did           |                src/commands/did.rs:156 | StoreTheirDid command received  DEBUG|indy::commands::did           |                src/commands/did.rs:285 | store_their_did >>> wallet_handle: 3, their_did_info_json: "\{\"did\":\"MEWn6Vh1KsdkSZvHTvuGQG\",\"verkey\":\"C2c5BptNrcgb9usyck8TKNhq3xFmMvZZA3SZpmW4kLXP\"}"  TRACE|indy::services::crypto        |         src/services/crypto/mod.rs:125 | create_their_did >>> their_did_info: TheirDidInfo \{ did: "MEWn6Vh1KsdkSZvHTvuGQG", verkey: Some("C2c5BptNrcgb9usyck8TKNhq3xFmMvZZA3SZpmW4kLXP") }  TRACE|indy::services::crypto        |         src/services/crypto/mod.rs:366 | validate_key >>> vk: "C2c5BptNrcgb9usyck8TKNhq3xFmMvZZA3SZpmW4kLXP"  TRACE|indy::services::crypto        |         src/services/crypto/mod.rs:386 | validate_key <<< res: ()  TRACE|indy::services::crypto        |         src/services/crypto/mod.rs:137 | create_their_did <<< did: TheirDid \{ did: "MEWn6Vh1KsdkSZvHTvuGQG", verkey: "C2c5BptNrcgb9usyck8TKNhq3xFmMvZZA3SZpmW4kLXP" }  ERROR|indy::errors::indy            |                 src/errors/indy.rs:73  | Casting error to ErrorCode: Item already exists  TRACE|indy::api::did                |                     src/api/did.rs:235 | indy_store_their_did:  TRACE|indy::api::did                |                     src/api/did.rs:222 | indy_store_their_did: >>> wallet_handle: 3, identity_json: 0x7ff56407a760  TRACE|indy::api::did                |                     src/api/did.rs:227 | indy_store_their_did: entities >>> wallet_handle: 3, identity_json: "\{\"did\":\"A2qGr9iVVrWsn3SwS2rg7w\",\"verkey\":\"5vWNZ26MXkydJsvdaTJ7Mo4AtfNFqJ9ETxSuEcxwUYXm\"}"  TRACE|indy::api::did                |                     src/api/did.rs:242 | indy_store_their_did: <<< res: Success  INFO|indy::commands                |                src/commands/mod.rs:122 | DidCommand command received  INFO|indy::commands::did           |                src/commands/did.rs:156 | StoreTheirDid command received  DEBUG|indy::commands::did           |                src/commands/did.rs:285 | store_their_did >>> wallet_handle: 3, their_did_info_json: "\{\"did\":\"A2qGr9iVVrWsn3SwS2rg7w\",\"verkey\":\"5vWNZ26MXkydJsvdaTJ7Mo4AtfNFqJ9ETxSuEcxwUYXm\"}"  TRACE|indy::services::crypto        |         src/services/crypto/mod.rs:125 | create_their_did >>> their_did_info: TheirDidInfo \{ did: "A2qGr9iVVrWsn3SwS2rg7w", verkey: Some("5vWNZ26MXkydJsvdaTJ7Mo4AtfNFqJ9ETxSuEcxwUYXm") }  TRACE|indy::services::crypto        |         src/services/crypto/mod.rs:366 | validate_key >>> vk: "5vWNZ26MXkydJsvdaTJ7Mo4AtfNFqJ9ETxSuEcxwUYXm"  TRACE|indy::services::crypto        |         src/services/crypto/mod.rs:386 | validate_key <<< res: ()  TRACE|indy::services::crypto        |         src/services/crypto/mod.rs:137 | create_their_did <<< did: TheirDid \{ did: "A2qGr9iVVrWsn3SwS2rg7w", verkey: "5vWNZ26MXkydJsvdaTJ7Mo4AtfNFqJ9ETxSuEcxwUYXm" }  ERROR|indy::errors::indy            |                 src/errors/indy.rs:73  | {color:#ff0000}*Casting error to ErrorCode: Wallet storage error occurred. Description: IO error during storage operation: cannot start a transaction within a transaction*{color}  TRACE|indy::api::did                |                     src/api/did.rs:235 | indy_store_their_did:  ></body> </Action>
<Action id="46957" issue="31666" author="rajeshkalaria" type="comment" created="2018-07-05 14:51:10.0" updateauthor="rajeshkalaria" updated="2018-07-05 14:52:03.0"> <body><! CDATA  ~gudkov   Able to reproduce the issue:  1. Try 'storeTheirDid' operation with say did1 and verkey1  2. Repeat above operation (with same did and ver key used in #1) but this time catch and swallow the exception (it will throw the exception WalletItemAlreadyExistsException)  3. Then, now if you try 'storeTheirDid' operation (either with same did and verkey or you can choose different did and verkey), it fails with error 'Storage error occurred during wallet operation.'  ></body> </Action>
<Action id="47038" issue="31666" author="gudkov" type="comment" body="Was able to reproduce this with the test." created="2018-07-06 14:13:35.0" updateauthor="gudkov" updated="2018-07-06 14:14:02.0"/>
<Action id="47044" issue="31666" author="gudkov" type="comment" created="2018-07-06 15:13:18.0" updateauthor="gudkov" updated="2018-07-06 15:13:18.0"> <body><! CDATA Cause:  - Our custom transaction object doesn't perform transaction rollback on Drop that causes the issue. As result any unsuccessful write to the wallet causes this error  Changes:  - Added the tests that reproduces IS-802 - Implemented rollback and corresponded Drop behavior for transaction object.  PR:  - https://github.com/hyperledger/indy-sdk/pull/929  ></body> </Action>
<Action id="47086" issue="31666" author="gudkov" type="comment" body="PR merged, tests passed" created="2018-07-09 09:43:31.0" updateauthor="gudkov" updated="2018-07-09 09:43:31.0"/>
