<Issue id="33046" key="IS-901" number="901" project="10401" reporter="ckochenower" assignee="gudkov" creator="ckochenower" type="10004" summary="Indy CLI does not see wallets created by Indy SDK" priority="3" resolution="10000" status="10001" created="2018-08-20 16:56:12.0" updated="2018-09-19 14:34:55.0" resolutiondate="2018-09-19 14:34:55.0" votes="0" watches="2" workflowId="51514"> <environment><! CDATA $ pip3 freeze | grep indy python3-indy==1.5.0.dev620  $ sudo apt list --installed | grep indy indy-cli/xenial,now 1.6.1~701 amd64  installed,upgradable to: 1.6.2~713  libindy/xenial,now 1.6.1~701 amd64  installed,upgradable to: 1.6.2~713  libindy-crypto/xenial,now 0.4.1~53 amd64  installed,upgradable to: 0.4.3   ></environment> <description><! CDATA Indy CLI does not see wallets created by Indy SDK.  Steps to reproduce:  1. Login to a client with indy-cli and Indy SDK (python wrappers) installed. We will assume user `ubuntu`. By default, wallets will be created in /home/ubuntu/.indy_client/wallet. 2. Use Indy SDK to create a wallet with name "chaosindy". Once created, the contents of ~/.indy_client will be the following: {code} . └── wallet └── chaosindy └── sqlite.db {code}  3. Use Indy CLI to list all wallets. The following will be displayed: {code} indy> wallet list There are no wallets {code}  4. Try to create a wallet named "chaosindy" using Indy CLI. The following will be displayed: {code} indy> wallet create chaosindy key=chaosindy Wallet "chaosindy" already exists {code}  The following screenshot depicts the overall results. indy-cli is running in the terminal on the left and `cd ~/.indy_client && watch -n2 'tree'` is being run in the terminal on the right.  !Screen Shot 2018-08-20 at 10.48.10 AM.png|thumbnail!    Note that wallets that are created with Indy CLI have no problems when used by Indy SDK. This is strictly a problem encountered when trying to use wallets created by Indy SDK within Indy CLI.  ></description> </Issue>
