<Action id="60405" issue="39849" author="ashcherbakov" type="comment" created="2019-05-27 07:27:17.0" updateauthor="ashcherbakov" updated="2019-05-27 07:27:17.0"> <body><! CDATA Looks like we need to re-run the test  Â   ></body> </Action>
<Action id="60465" issue="39849" author="vladimirwork" type="comment" created="2019-05-29 16:05:09.0" updateauthor="vladimirwork" updated="2019-05-29 16:05:09.0"> <body><! CDATA Build Info: indy-node 1.8.0~dev981 plugins 0.9.12~38  Steps to Reproduce: 1. Run production load test with fees and spikes: {noformat} for s in `seq 1 100` ; do perf_processes.py -g persistent_transactions_genesis -m t -n 1 -y one -s 000000000000000000000000Trustee1 -s 000000000000000000000000Trustee2 -s 000000000000000000000000Trustee3 -s 000000000000000000000000Trustee4 --ext "{\"payment_addrs_count\":10,\"addr_mint_limit\":1000000,\"mint_by\":250000,\"payment_method\":\"sov\",\"plugin_lib\":\"libsovtoken.so\",\"plugin_init\":\"sovtoken_init\",\"trustees_num\":4,\"set_fees\":{\"1\":1,\"100\":1,\"101\":1,\"102\":1,\"113\":1,\"10001\":1}}" -k " {\"nym\":{\"count\": 4}}, {\"schema\":{\"count\": 1}}, {\"attrib\":{\"count\": 3}}, {\"cred_def\":{\"count\": 1}}, {\"revoc_reg_def\":{\"count\": 1}}, {\"payment\":{\"count\": 9}} " -c 10 -b 10 -l 10 --short_stat --log_lvl 50 --load_time 10800 ; sleep 1800 ; done {noformat}   Actual Results: There are OOM errors on several nodes and too many failed and nacked txns on writing client: {noformat} Clients 10/10 Sent: 35227 Succ: 24107 Failed: 1896 Nacked: 9101 Rejected: 0 {noformat}  Logs: ev@evernymr33:logs/acceptance_prod_load_fees_spikes_29_05_2019_logs.tar.gz  ></body> </Action>
<Action id="60572" issue="39849" author="vladimirwork" type="comment" body="There was a much bigger load rate than expected in previous case. Retesting with 0 to 10 txns/sec spikes looks good (there are no rejects or fails during 8 hours)." created="2019-06-01 09:58:24.0" updateauthor="vladimirwork" updated="2019-06-01 09:58:24.0"/>
