<Action id="45206" issue="30672" author="phulei" type="comment" created="2018-05-28 20:05:10.0" updateauthor="phulei" updated="2018-05-28 20:05:10.0"> <body><! CDATA some more info :     cello-user-dashboard | 20:03:25 0|index |  2018-05-28 20:03:25.375   ERROR  Join-Channel - TypeError: Cannot read property 'getConnectivityState' of undefined cello-user-dashboard | 20:03:25 0|index | at EventHub._checkConnection (/node_modules/fabric-client/lib/EventHub.js:479:39) cello-user-dashboard | 20:03:25 0|index | at EventHub.registerBlockEvent (/node_modules/fabric-client/lib/EventHub.js:658:8) cello-user-dashboard | 20:03:25 0|index | at Promise (/opt/data/users/admin/chains/5b0c6089a786470062ab9739/lib/join-channel.js:83:8) cello-user-dashboard | 20:03:25 0|index | at new Promise (<anonymous>) cello-user-dashboard | 20:03:25 0|index | at eventhubs.forEach.eh (/opt/data/users/admin/chains/5b0c6089a786470062ab9739/lib/join-channel.js:81:20) cello-user-dashboard | 20:03:25 0|index | at Array.forEach (<anonymous>) cello-user-dashboard | 20:03:25 0|index | at helper.getOrgAdmin.then.then.genesis_block (/opt/data/users/admin/chains/5b0c6089a786470062ab9739/lib/join-channel.js:80:13) cello-user-dashboard | 20:03:25 0|index | at <anonymous> cello-user-dashboard | 20:03:25 0|index | at process._tickDomainCallback (internal/process/next_tick.js:228:7) cello-user-dashboard | 20:03:25 0|index |  2018-05-28 20:03:25.375   DEBUG  Join-Channel - cello-user-dashboard | 20:03:25 0|index | !!!!!!!! ERROR: Join Channel FAILED !!!!!!!! cello-user-dashboard | 20:03:25 0|index |  2018-05-28 20:03:25.375   DEBUG  Join-Channel - cello-user-dashboard | 20:03:25 0|index | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection: cello-user-dashboard | 20:03:25 0|index | Error: TypeError: Cannot read property 'getConnectivityState' of undefined cello-user-dashboard | 20:03:25 0|index | at EventHub._checkConnection (/node_modules/fabric-client/lib/EventHub.js:479:39) cello-user-dashboard | 20:03:25 0|index | at EventHub.registerBlockEvent (/node_modules/fabric-client/lib/EventHub.js:658:8) cello-user-dashboard | 20:03:25 0|index | at Promise (/opt/data/users/admin/chains/5b0c6089a786470062ab9739/lib/join-channel.js:83:8) cello-user-dashboard | 20:03:25 0|index | at new Promise (<anonymous>) cello-user-dashboard | 20:03:25 0|index | at eventhubs.forEach.eh (/opt/data/users/admin/chains/5b0c6089a786470062ab9739/lib/join-channel.js:81:20) cello-user-dashboard | 20:03:25 0|index | at Array.forEach (<anonymous>) cello-user-dashboard | 20:03:25 0|index | at helper.getOrgAdmin.then.then.genesis_block (/opt/data/users/admin/chains/5b0c6089a786470062ab9739/lib/join-channel.js:80:13) cello-user-dashboard | 20:03:25 0|index | at <anonymous> cello-user-dashboard | 20:03:25 0|index | at process._tickDomainCallback (internal/process/next_tick.js:228:7) cello-user-dashboard | 20:03:25 0|index | at helper.getOrgAdmin.then.then.then.err (/opt/data/users/admin/chains/5b0c6089a786470062ab9739/lib/join-channel.js:132:9) cello-user-dashboard | 20:03:25 0|index | at <anonymous> cello-user-dashboard | 20:03:25 0|index | at process._tickDomainCallback (internal/process/next_tick.js:228:7) cello-user-dashboard | 20:03:25 0|index | TypeError: Cannot read property 'getConnectivityState' of undefined cello-user-dashboard | 20:03:25 0|index | at ClientDuplexStream.<anonymous> (/node_modules/fabric-client/lib/EventHub.js:308:56) cello-user-dashboard | 20:03:25 0|index | at emitOne (events.js:116:13) cello-user-dashboard | 20:03:25 0|index | at ClientDuplexStream.emit (events.js:211:7) cello-user-dashboard | 20:03:25 0|index | at addChunk (_stream_readable.js:263:12) cello-user-dashboard | 20:03:25 0|index | at readableAddChunk (_stream_readable.js:250:11) cello-user-dashboard | 20:03:25 0|index | at ClientDuplexStream.Readable.push (_stream_readable.js:208:10) cello-user-dashboard | 20:03:25 0|index | at Object.onReceiveMessage (/node_modules/grpc/src/client_interceptors.js:1302:19) cello-user-dashboard | 20:03:25 0|index | at InterceptingListener.recvMessageWithContext (/node_modules/grpc/src/client_interceptors.js:629:19) cello-user-dashboard | 20:03:25 0|index | at /node_modules/grpc/src/client_interceptors.js:728:14 cello-dashboard_mongo | 2018-05-28T20:03:25.812+0000 I -  conn5  end connection 172.18.0.7:39010 (2 connections now open) cello-user-dashboard |  2018-05-28 20:03:25  PM2 log: App  index  with id  0  and pid  92 , exited with code  1  via signal  SIGINT   ></body> </Action>
<Action id="46142" issue="30672" author="phulei" type="comment" body=" ~yeasy  - could you please check and let me know how to update fabric sdk " created="2018-06-18 18:49:44.0" updateauthor="phulei" updated="2018-06-18 18:49:44.0"/>
<Action id="46170" issue="30672" author="baohua" type="comment" created="2018-06-19 01:06:24.0" updateauthor="baohua" updated="2018-06-19 01:07:08.0"> <body><! CDATA hmm, it seems the SDK version problem.   ~hightall , do we have some manual way to fix the problem quickly?   ~phulei , thanks for ur reporting. Is it working with the latest code at master branch?  ></body> </Action>
<Action id="46219" issue="30672" author="phulei" type="comment" body=" ~baohua  yes , facing the same issue with the master branch,  ~hightall  great if you could let me know how to update the image tags. waiting for your response." created="2018-06-19 15:52:34.0" updateauthor="phulei" updated="2018-06-19 15:52:34.0"/>
<Action id="46222" issue="30672" author="hightall" type="comment" created="2018-06-19 16:02:22.0" updateauthor="hightall" updated="2018-06-19 16:02:22.0"> <body><! CDATA we have fix this problem, please use version 0.8.0 image to run.  in master node  1. git clone -b v0.8.0 --depth 1  https://github.com/hyperledger/cello.git   2. VERSION=0.8.0 make dockerhub-pull  3. make start  in worker node  1. git clone -b v0.8.0 --depth 1  https://github.com/hyperledger/cello.git   2. make setup-worker  ></body> </Action>
<Action id="46225" issue="30672" author="phulei" type="comment" created="2018-06-19 16:59:41.0" updateauthor="phulei" updated="2018-06-19 16:59:41.0"> <body><! CDATA thank you  ~hightall  !   facing the same error and this time the logs are bit different   cello-user-dashboard | 16:58:16 0|index | error:  client-utils.js : sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: could not find chaincode with name 'c42cbe481c1c4a049d2f865210a3e36e-5b293113afce220029a6a478' - make sure the chaincode c42cbe481c1c4a049d2f865210a3e36e-5b293113afce220029a6a478 has been successfully instantiated and try againcello-user-dashboard | 16:58:16 0|index | at new createStatusError (/node_modules/grpc/src/client.js:64:15)cello-user-dashboard | 16:58:16 0|index | at /node_modules/grpc/src/client.js:583:15cello-user-dashboard | 16:58:16 0|index |  2018-06-19 16:58:16.553   ERROR  invoke-chaincode - transaction proposal was badcello-user-dashboard | 16:58:16 0|index |  2018-06-19 16:58:16.553   ERROR  invoke-chaincode - Failed to send Proposal or receive valid response. Response null or status is not 200. exiting...cello-user-dashboard | 16:58:16 0|index |  2018-06-19 16:58:16.554   ERROR  invoke-chaincode - Failed to order the transaction. Error code: undefined  ></body> </Action>
<Action id="46297" issue="30672" author="phulei" type="comment" body=" ~hightall  - still facing error, could you please provide some guidence here ?" created="2018-06-20 15:21:48.0" updateauthor="phulei" updated="2018-06-20 15:21:48.0"/>
<Action id="46332" issue="30672" author="hightall" type="comment" body=" ~phulei  please remove move in parameter" created="2018-06-21 01:18:31.0" updateauthor="hightall" updated="2018-06-21 01:18:31.0"/>
<Action id="46470" issue="30672" author="rtrive" type="comment" created="2018-06-23 09:50:08.0" updateauthor="rtrive" updated="2018-06-23 10:02:13.0"> <body><! CDATA Hi, i'm still facing the same error even if i try with your suggest  ~hightall . I can install the smartcode but when i try to instantiate i found errros and i can invoke any function.     The Cello dashboard give me this  !2018-06-23 11_52_58-Chain.png|thumbnail!  !2018-06-23 11_52_28-Chain.png|thumbnail!  !2018-06-23 11_52_18-Chain.png|thumbnail!  This is logs for the error {code:java} // cello-user-dashboard  | 09:41:59 0|index    | error:  Peer.js : sendProposal - timed out after:45000 cello-user-dashboard  | 09:41:59 0|index    | error:  Peer.js : sendProposal - timed out after:45000 cello-user-dashboard  | 09:41:59 0|index    | error:  client-utils.js : sendPeersProposal - Promise is rejected: Error: REQUEST_TIMEOUT cello-user-dashboard  | 09:41:59 0|index    |     at Timeout._onTimeout (/node_modules/fabric-client/lib/Peer.js:117:19) cello-user-dashboard  | 09:41:59 0|index    |     at ontimeout (timers.js:478:11) cello-user-dashboard  | 09:41:59 0|index    |     at tryOnTimeout (timers.js:302:5) cello-user-dashboard  | 09:41:59 0|index    |     at Timer.listOnTimeout (timers.js:262:5) cello-user-dashboard  | 09:41:59 0|index    | error:  client-utils.js : sendPeersProposal - Promise is rejected: Error: REQUEST_TIMEOUT cello-user-dashboard  | 09:41:59 0|index    |     at Timeout._onTimeout (/node_modules/fabric-client/lib/Peer.js:117:19) cello-user-dashboard  | 09:41:59 0|index    |     at ontimeout (timers.js:478:11) cello-user-dashboard  | 09:41:59 0|index    |     at tryOnTimeout (timers.js:302:5) cello-user-dashboard  | 09:41:59 0|index    |     at Timer.listOnTimeout (timers.js:262:5) cello-user-dashboard  | 09:41:59 0|index    |  2018-06-23 09:41:59.888   ERROR  instantiate-chaincode - instantiate proposal was bad cello-user-dashboard  | 09:41:59 0|index    |  2018-06-23 09:41:59.891   ERROR  instantiate-chaincode - instantiate proposal was bad cello-user-dashboard  | 09:41:59 0|index    |  2018-06-23 09:41:59.891   ERROR  instantiate-chaincode - Failed to send instantiate Proposal or receive valid response. Response null or status is not 200. exiting... cello-user-dashboard  | 09:41:59 0|index    |  2018-06-23 09:41:59.896   ERROR  instantiate-chaincode - Failed to order the transaction. Error code: undefined {code} and this the log when i try to query smart contract. From logs it seems that the instantiate phase dit not run correctly    {code:java} cello-user-dashboard  | 09:59:09 0|index    | error:  client-utils.js : sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: could not find chaincode with name '2fc4cde1fa504e4cad35fe3bcf8c1d86-5b2e144ec78d1200338095fb' - make sure the chaincode 2fc4cde1fa504e4cad35fe3bcf8c1d86-5b2e144ec78d1200338095fb has been successfully instantiated and try again cello-user-dashboard  | 09:59:09 0|index    |     at new createStatusError (/node_modules/grpc/src/client.js:64:15) cello-user-dashboard  | 09:59:09 0|index    |     at /node_modules/grpc/src/client.js:583:15 cello-user-dashboard  | 09:59:09 0|index    | error:  client-utils.js : sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: could not find chaincode with name '2fc4cde1fa504e4cad35fe3bcf8c1d86-5b2e144ec78d1200338095fb' - make sure the chaincode 2fc4cde1fa504e4cad35fe3bcf8c1d86-5b2e144ec78d1200338095fb has been successfully instantiated and try again cello-user-dashboard  | 09:59:09 0|index    |     at new createStatusError (/node_modules/grpc/src/client.js:64:15) cello-user-dashboard  | 09:59:09 0|index    |     at /node_modules/grpc/src/client.js:583:15 cello-user-dashboard  | 09:59:09 0|index    |  2018-06-23 09:59:09.424   INFO  Query - a now has Error: 2 UNKNOWN: could not find chaincode with name '2fc4cde1fa504e4cad35fe3bcf8c1d86-5b2e144ec78d1200338095fb' - make sure the chaincode 2fc4cde1fa504e4cad35fe3bcf8c1d86-5b2e144ec78d1200338095fb has been successfully instantiated and try again after the move {code}  ></body> </Action>
<Action id="47762" issue="30672" author="baohua" type="comment" body="Is the problem still there?" created="2018-07-25 06:16:59.0" updateauthor="baohua" updated="2018-07-25 06:16:59.0"/>
