<Issue id="42000" key="INDY-2215" number="2215" project="10303" reporter="vladimirwork" assignee="vladimirwork" creator="vladimirwork" type="10004" summary="One node doesn&apos;t catch up" priority="3" resolution="10000" status="10001" created="2019-08-23 07:05:20.0" updated="2019-08-28 15:10:09.0" resolutiondate="2019-08-28 15:10:09.0" votes="0" watches="2" workflowId="55042"> <description><! CDATA Build Info: indy-node 1.9.2~dev1061  Steps to Reproduce: https://github.com/hyperledger/indy-test-automation/blob/931ad5f2ac070f325bf3708d5cc48bfb158e643a/system/indy-node-tests/TestAuditSuite.py#L13  Actual Results: 6th node doesn't catch up after all restarts in 200 seconds.  Expected Results: All nodes should catch up at the end of test.  ></description> </Issue>
