<Issue id="27466" key="FAB-8091" number="8091" project="10002" reporter="nishi" assignee="sanchezl" creator="nishi" type="10004" summary="During execution of FAB- 7913:  logs should indicate failure is due to difference in shim versions" priority="3" resolution="10000" status="6" created="2018-02-06 22:29:31.0" updated="2018-07-20 14:15:38.0" resolutiondate="2018-02-14 16:39:19.0" votes="0" watches="4" workflowId="41141"> <description><! CDATA When testing with a chaincode that has vendored  1.0.x shim using:   https://github.com/ghaskins/hyperledger-fabric-alpha2-challenge/tree/master/jyellick/plob/   *Steps to Reproduce:*  From "github.com/hyperledger/fabric-test/feature-upgrade/features/upgrade-abort.feature" file use the above chaincode and implement the below scenario {code:java} https://jira.hyperledger.org/browse/FAB-7913  1. Start a v1.0.x peer 2. Deploy a chaincode which vendors a v1.0.x chaincode shim. 3. Shut down the peer 4. Delete the chaincode image 5. Upgrade the peer to v1.1.0 6. Start up the peer 7. Attempt to query the chaincode{code}       *Actual Result:* Use case fails as expected @step7  when we look at:  *1. chaincode logs:* {code:java} 2018-02-06 21:44:57.257 UTC  shim  userChaincodeStreamGetter -> ERRO 001 Error trying to connect to local peer: remote error: tls: bad certificate Error starting PermissionedBlobRegistry chaincode: Error trying to connect to local peer: remote error: tls: bad certificatenishi@nishi-VirtualBox:~/gopath/src/github.com/hyperledger/fabric-release/examples/chaincode/go/hyperledger-fabric-alpha2-challenge/jyellick/plob/chaincode${code}    2. *peer logs*  After 5 minutes of failure following was reported in peer logs: {code:java}  2018-02-06 21:49:42.275 UTC  endorser  callChaincode -> DEBU 474  com.acme.blockchain.jdoe.channel1  e5437651  Exit 2018-02-06 21:49:42.275 UTC  endorser  simulateProposal -> ERRO 475  com.acme.blockchain.jdoe.channel1  e5437651  failed to invoke chaincode path:"github.com/hyperledger/fabric-release/examples/chaincode/go/hyperledger-fabric-alpha2-challenge/jyellick/plob/chaincode" name:"example02_vendor" version:"1.0" , error: timeout expired while starting chaincode example02_vendor:1.0(networkid:ee28cd0a0b8511e8837b0800277dd479,peerid:vp0,tx:e54376518a555732a11141d1b89033c67afc32296251cb0e477fe6f753047d6b) github.com/hyperledger/fabric/core/chaincode.(*ChaincodeSupport).launchAndWaitForRegister /opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/chaincode_support.go:567 github.com/hyperledger/fabric/core/chaincode.(*ChaincodeSupport).Launch /opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/chaincode_support.go:729 github.com/hyperledger/fabric/core/chaincode.Execute /opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/exectransaction.go:45 github.com/hyperledger/fabric/core/chaincode.ExecuteChaincode /opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/chaincodeexec.go:85 github.com/hyperledger/fabric/core/endorser.(*SupportImpl).Execute /opt/gopath/src/github.com/hyperledger/fabric/core/endorser/support.go:93 github.com/hyperledger/fabric/core/endorser.(*Endorser).callChaincode /opt/gopath/src/github.com/hyperledger/fabric/core/endorser/endorser.go:123 github.com/hyperledger/fabric/core/endorser.(*Endorser).simulateProposal /opt/gopath/src/github.com/hyperledger/fabric/core/endorser/endorser.go:256 github.com/hyperledger/fabric/core/endorser.(*Endorser).ProcessProposal /opt/gopath/src/github.com/hyperledger/fabric/core/endorser/endorser.go:458 github.com/hyperledger/fabric/core/handlers/auth/filter.(*expirationCheckFilter).ProcessProposal /opt/gopath/src/github.com/hyperledger/fabric/core/handlers/auth/filter/expiration.go:61 github.com/hyperledger/fabric/core/handlers/auth/filter.(*filter).ProcessProposal /opt/gopath/src/github.com/hyperledger/fabric/core/handlers/auth/filter/filter.go:31 github.com/hyperledger/fabric/protos/peer._Endorser_ProcessProposal_Handler /opt/gopath/src/github.com/hyperledger/fabric/protos/peer/peer.pb.go:112 github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*Server).processUnaryRPC /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/server.go:781 github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*Server).handleStream /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/server.go:981 github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1 /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/server.go:551 runtime.goexit /opt/go/src/runtime/asm_amd64.s:2337 error executing chaincode {code} *Expected Result:*     When step 7 above fails error messages reported in peer log are not indicating about the chaincode query failure as being related to difference in shim version after upgrade of fabric from step 5 .   Can the user be notified that error is occurring because of difference in shim version?  ></description> </Issue>
